### PR TITLE
let connect() always return a boolean status

### PR DESCRIPTION
**Pull request by derpue**
removing small inconsistency with return value in connect() method

### CODE REVIEW

**Comment by mgp25** [comment]
We have already the function `isConnected()` that returns `false` if not connected, otherwise it will return `true`. If you have enhacement or see something that could be improved, feel free to send a pull request.

Regards

**Comment by derpue** [comment]
Please have a second look at the code of `connect()` and the small proposed change.

First it checks if it is already connected (via `$this->isConnected()`).
If it is already connected it **returns true**. 
If it is not connected it tries to open the socket and - depending of the outcome - fires the `onConnect` or `onConnectError` Events, but in both cases **returns nothing**.

So we have here a small inconsistency beside the inconvenient usage.
Yes, we have the Events, but since `connet()` is a "blocking" call, these are (at least for me) not really needed.

Why use
```php
$w->connet();
if ($w->isConnected()) {}
```
instead a single
```php
if ($w->connect()) {}
```
or more worse
```php
$w->connect();
while (!$w->isConnected()) {
    sleep(10);
    $w->connect();
}
```
instead of
```php
while (!$w->connect())
    sleep(10);
```
especially when it won't break any existing code?

**Comment by mgp25** [comment]
As the code has changed, can you send a new pull request? Ill merge it

Thanks

Regards

**Comment by mgp25** [comment]
Ignore my last comment* 

Thanks

Regards

**Pull request merged**
